### ISSUE TITLE
Set up a host

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci/digital-display-garden#5]
What we need is:

* A physical box or VM or software container running Linux
* At least ?GB of RAM
   * I don't honestly remember the number here, but I think we needed something like 4-8GB of RAM (or RAM + virtual memory) for Node to be able to do its thing
* Root access for a physical box or VM; we'd sort of get that "for free" on a container (I think).

Options include 

* Just running a small local box up at WCROC
* An [OIT hosted Virtual Machine](https://it.umn.edu/hosting-services)
   * I think a [fully managed system](https://it.umn.edu/fully-managed-server-hosting) would be a pain because we'd have to go through them to get every little thing updated/modified, but I could be wrong. It looks like we can do `yum install` to install packages, so if we can use that to install Mongo and if we have enough power to properly configure Mongo, when the rest might sort itself out.
   * A more plausible sounding option are what they call [jointly managed systems](https://it.umn.edu/jointly-managed-server-hosting) since that seems to be designed for people doing their own deployment (which seems to be us). They say, though, that these are expected to be stateless, which means that the DB can't be hosted there. We can't use their [database hosting service](https://it.umn.edu/database-hosting) without some substantial changes to the code because what they support is all SQL based. We can (I think) use a fully managed system with Mongo on it, and have our web server point to that, but then we'd also need to set up proper authentication and credentials on the Mongo instance (instead of just saying anyone on `localhost` can access it).

**Comment by NicMcPhee** [comment]
I've emailed the tech person at WCROC about their preferences. They're super busy at the moment, though, so we might not hear back right away.

**Comment by danfrz** [comment]
I remember we had to up the swap space so that we wouldn't run out of memory doing some RAM intensive tests (importing/patching spreadsheet, qr-code generation). On the droplet we have 488 MB ram and 6 GB swap. Depending on how much RAM we get, we might want to up swap a little bit because iirc one of the tests still failed from OutOfMemory (?)

**Comment by NicMcPhee** [comment]
We had a variety of issues getting this set up on U of M infrastructure, so for the 2017 season we're going on a Digital Ocean droplet that I'm paying for. The U folks were able to set up a nice domain name for us, though, which routes to the droplet.
